site_name: Data Campus
# site_url:
theme:
  name: material
  logo: assets/logo1.png
  favicon: assets/icon.png
  palette:
    - scheme: slate
      primary: custom  # teal
      accent: custom  # peachy peach
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    - scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.indexes
    - navigation.tabs
    - navigation.tabs.sticky
    - content.code.copy
    - content.code.annotate
    - navigation.footer
    - navigation.top  # 'back to top' button on scrolling
    - header.autohide
    - search.highlight
nav:
  - Home: index.md

  - Data:
    - Home: data/index.md
    - Einführung: data/einfuehrung.md
    - Datenerfassung: data/datenerfassung.md
    - Datenverarbeitung: data/zahlensysteme.md
    - Speicherung: data/speicherung.md

  - Excel:
    - Home: excel/index.md
    
  - Database:
    - Home: database/index.md
    - Einführung: database/einfuehrung.md
    - Relational: database/relational.md
    - Abfragen: database/abfragen.md
    - Manipulieren: database/manipulieren.md
    - Modellierung: database/modellierung.md
    - Join: database/join.md
    - Fortgeschritten: database/fortgeschritten.md
    - Integrität: database/integritaet.md
    - Indizes: database/indizes.md
    - Transaktionen: database/transaktionen.md
    - Projekt: database/projekt.md
    - Ausblick: database/ausblick.md


extra_css:
  - stylesheets/colors.css
  - stylesheets/extra.css

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - md_in_html
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js