site_name: Data Campus
# site_url:
theme:
  name: material
  logo: assets/icon.png
  favicon: assets/icon.png
  palette:
    - scheme: slate
      primary: custom  # teal
      accent: custom  # peachy peach
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    - scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.indexes
    - navigation.tabs
    - navigation.tabs.sticky
    - content.code.copy
    - content.code.annotate
    - navigation.footer
    - navigation.top  # 'back to top' button on scrolling
    - header.autohide
    - search.highlight
nav:
  - Home: index.md

  - Excel:
    - Home: excel/index.md
  - Datammbase:
    - Home: database/index.md
  - Data:
    - Home: data/index.md

extra_css:
  - stylesheets/colors.css