[project]
name = "data-campus"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "mkdocs-glightbox>=0.5.2",
    "mkdocs-material>=9.6.20",
]
